// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "ProEye — Structural Excellence",
  description: "Structural excellence delivered with integrity.",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={poppins.variable}>
//       <body className="min-h-screen bg-gradient-to-br from-gray-950 via-brand-blue to-black text-white antialiased">
//         <head>
//   ...
//   {(process.env.NODE_ENV === "development" || process.env.VERCEL_ENV === "preview") && (
//     // eslint-disable-next-line @next/next/no-sync-scripts
//     <script
//       data-recording-token="BvxUtLv9Uwz7XlWkwt1QvRBI8g994sTBM1jPvAq5"
//       data-is-production-environment="false"
//       src="https://snippet.meticulous.ai/v1/meticulous.js"
//     />
//   )}
//   ...
// </head>
//         {children}
//       </body>
//     </html>
//   );
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        {(process.env.NODE_ENV === "development" ||
          process.env.VERCEL_ENV === "preview") && (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script
            data-recording-token="BvxUtLv9Uwz7XlWkwt1QvRBI8g994sTBM1jPvAq5"
            data-is-production-environment="false"
            src="https://snippet.meticulous.ai/v1/meticulous.js"
          />
        )}
      </head>
      <body className="min-h-screen bg-gradient-to-br from-gray-950 via-brand-blue to-black text-white antialiased">
        {children}
      </body>
    </html>
  );
}
